Check brew formulae exists before installing

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -25,6 +25,14 @@ function e_warning() {
     printf "$(tput setaf 136)! %s$(tput sgr0)\n" "$@"
 }
 
+# Check to see if a `brew` formulae is installed
+function formula_exists() {
+    if $(brew list $1 >/dev/null); then
+        return 0
+    fi
+    return 1
+}
+
 # Check to see if we are running on a Mac
 if [ "$(uname -s | grep -c Darwin)" -gt 0 ]; then
 
@@ -35,24 +43,46 @@ if [ "$(uname -s | grep -c Darwin)" -gt 0 ]; then
     fi
 
     # Make sure we have the most up to date version of homebrew
-    e_header "Updating Homebrew"
+    e_header "Updating Homebrew..."
     brew update
 
     # Update any existing formulae
-    e_header "Updating Homebrew formulae"
-    brew upgrade
+    brew upgrade --all
 
-    # Install required formulae
-    e_header "Checking status of desired Homebrew formulae..."
-    brew install \
-        coreutils \
-        git \
-        ack \
-        bash \
-        bash-completion \
-        grep \
-        tree \
-        wget
+    # Determine a list of formulae to install
+    declare LIST_FORMULAE
+    declare -a MISSING_FORMULAE
+    declare -a DESIRED_FORMULAE=(
+        'coreutils'
+        'git'
+        'ack'
+        'bash'
+        'bash-completion'
+        'grep'
+        'tree'
+        'wget'
+    )
+
+    # Create the `MISSING_FORMULAE` list
+    for index in ${!DESIRED_FORMULAE[*]}
+    do
+        if ! formula_exists ${DESIRED_FORMULAE[$index]}; then
+            # Store the name (and options) of every missing formula
+            MISSING_FORMULAE=("${MISSING_FORMULAE[@]}" "${DESIRED_FORMULAE[$index]}")
+        fi
+    done
+
+    # Install `MISSING_FORMULAE`
+    if [[ "$MISSING_FORMULAE" ]]; then
+
+        # Convert the array of missing formula into a list of space-separate strings
+        LIST_FORMULAE=$( printf "%s " "${MISSING_FORMULAE[@]}" )
+
+        # Install all missing formulae
+        e_header "Installing missing Homebrew formulae..."
+        brew install $LIST_FORMULAE
+
+    fi
 
     # Remove outdated versions from the Cellar
     brew cleanup
